package Consultas;


import org.apache.log4j.Logger;

public class FuncionesSqlQuery {
	
private static Logger log = Logger.getLogger(FuncionesSqlQuery.class);
	
	static ConexionBase dbconector = new ConexionBase();

	public static void ejecutarFuncionOriginacion() {
		log.info("***Ejecutando Funcion Originacion ***");
		try {
			dbconector.ejecutorFunciones(
					"create or replace\r\n"
					+ "function public.calculos_automatizacion_pruebas (\r\n"
					+ "  p_monto integer,\r\n"
					+ "p_xperiodoPrima integer,\r\n"
					+ "p_tasaInicial numeric,\r\n"
					+ "p_plazo numeric,\r\n"
					+ "p_diasIniciales numeric,\r\n"
					+ "p_vlrCompasSaneamientos numeric,\r\n"
					+ "p_ingresos numeric,\r\n"
					+ "p_descLey numeric,\r\n"
					+ "p_descNomina numeric,\r\n"
					+ "p_pagaduria text \r\n"
					+ ")\r\n"
					+ "returns table (\r\n"
					+ "r_monto_solicitar int,\r\n"
					+ "r_cuota_corriente int,\r\n"
					+ "r_estudio_credito_iva int,\r\n"
					+ "r_fianza int,\r\n"
					+ "r_gmf4100 int,\r\n"
					+ "r_valor_intereses_iniciales int,\r\n"
					+ "r_prima_anticipada_seguro int,\r\n"
					+ "r_remanente_estimado int,\r\n"
					+ "r_monto_max_desembolsar int,\r\n"
					+ "r_capacidad_cliente int\r\n"
					+ ")\r\n"
					+ "language plpgsql\r\n"
					+ "as $function$\r\n"
					+ "\r\n"
					+ "declare\r\n"
					+ "-- ============================================================================\r\n"
					+ "-- Autor: Equipo automatizacion Pruebas.\r\n"
					+ "-- Fecha: 08/Nov/2021 Version 1.0 ThainerPerez - Jonathan Varon\r\n"
					+ "-- Se crea la funcion que retorna los calculos de originacion para los simuladores\r\n"
					+ "-- ============================================================================\r\n"
					+ "\r\n"
					+ "\r\n"
					+ "/*VARIABLES GLOBALES PARA LOS PARAMETROS*/\r\n"
					+ "v_tasa_estudio_credito numeric;\r\n"
					+ "\r\n"
					+ "v_tasa_fianza numeric;\r\n"
					+ "\r\n"
					+ "v_vlr_mes_dos numeric;\r\n"
					+ "\r\n"
					+ "v_tasa_uno numeric = p_tasaInicial / 100 ;\r\n"
					+ "\r\n"
					+ "v_tasa_dos numeric;\r\n"
					+ "\r\n"
					+ "v_tasaXmillonSeguro numeric;\r\n"
					+ "\r\n"
					+ "v_valor_millon numeric = 1000000;\r\n"
					+ "\r\n"
					+ "v_iva numeric = 1.19;\r\n"
					+ "\r\n"
					+ "v_diasMes numeric = 30;\r\n"
					+ "\r\n"
					+ "v_gmf4100 numeric = 0.004;\r\n"
					+ "\r\n"
					+ "v_capacidad numeric;\r\n"
					+ "\r\n"
					+ "v_colchon numeric;\r\n"
					+ "\r\n"
					+ "begin\r\n"
					+ "/*PARAMETROS GLOBALES*/\r\n"
					+ "\r\n"
					+ "/*consultar valores capitalizados*/\r\n"
					+ "select\r\n"
					+ "	segunda_tasa,\r\n"
					+ "	estudio_credito,\r\n"
					+ "	fianza,\r\n"
					+ "	mes_cambio_tasa\r\n"
					+ "into\r\n"
					+ "	v_tasa_dos,\r\n"
					+ "	v_tasa_estudio_credito,\r\n"
					+ "	v_tasa_fianza,\r\n"
					+ "	v_vlr_mes_dos\r\n"
					+ "from\r\n"
					+ "	configuracion_capitalizacion_cxc ccc\r\n"
					+ "where\r\n"
					+ "	tasa_inicial = p_tasaInicial;\r\n"
					+ "\r\n"
					+ "/*consultar tasaXmillon*/\r\n"
					+ "select\r\n"
					+ "	tasa_millon\r\n"
					+ "into\r\n"
					+ "	v_tasaXmillonSeguro\r\n"
					+ "from\r\n"
					+ "	seguro;\r\n"
					+ "\r\n"
					+ "/*consultar colchon*/\r\n"
					+ "select\r\n"
					+ "	pp.valor\r\n"
					+ "into\r\n"
					+ "	v_colchon\r\n"
					+ "from\r\n"
					+ "	pagaduria p\r\n"
					+ "inner join pagaduria_parametro pp on\r\n"
					+ "	pp.id_pagaduria = p.id\r\n"
					+ "inner join parametro pa on\r\n"
					+ "	pa.id = pp.id_parametro\r\n"
					+ "where\r\n"
					+ "	p.nombre = p_pagaduria\r\n"
					+ "	and pa.nombre = 'colchon';\r\n"
					+ "\r\n"
					+ "/**********************************CALCULOS DE CONCEPTOS PARA SIMULADORES********************************************/\r\n"
					+ "   \r\n"
					+ "	/*Calcular monto solicitado -  originacion*/\r\n"
					+ "r_monto_solicitar := p_monto + (p_monto * v_tasaXmillonSeguro / v_valor_millon * p_xperiodoPrima)\r\n"
					+ "                + (p_monto * (v_tasa_estudio_credito / 100) * v_iva) + (p_monto * (v_tasa_fianza / 100) * v_iva);\r\n"
					+ "\r\n"
					+ "raise notice 'Monto solicitar %',\r\n"
					+ "(r_monto_solicitar);\r\n"
					+ "\r\n"
					+ "	/*Calcular cuota corriente -  originacion*/\r\n"
					+ "   if(p_plazo < v_vlr_mes_dos) then\r\n"
					+ "    r_cuota_corriente := r_monto_solicitar / ((power((1 + v_tasa_uno), (p_plazo)) - 1) / (v_tasa_uno * power((1 + v_tasa_uno), (p_plazo))));\r\n"
					+ "else\r\n"
					+ "	v_tasa_dos = v_tasa_dos / 100;\r\n"
					+ "   r_cuota_corriente := round(r_monto_solicitar\r\n"
					+ "                    / ((power((1 + v_tasa_uno), (v_vlr_mes_dos - 1)) - 1) / (v_tasa_uno * power((1 + v_tasa_uno), (v_vlr_mes_dos - 1)))\r\n"
					+ "                    + ((power((1 + v_tasa_dos), (p_plazo - (v_vlr_mes_dos - 1))) - 1)\r\n"
					+ "                    / (v_tasa_dos * power((1 + v_tasa_dos), (p_plazo - (v_vlr_mes_dos - 1)))))\r\n"
					+ "                    / (power((1 + v_tasa_uno), (v_vlr_mes_dos - 1)))));\r\n"
					+ "                   \r\n"
					+ "   /*raise notice '>>>> valor credito %', (r_monto_solicitar);\r\n"
					+ "  raise notice '>>>> valor tasaUno  %', (v_tasa_uno);\r\n"
					+ " raise notice '>>>> valor mesDos  %', (v_vlr_mes_dos);\r\n"
					+ " raise notice '>>>> valor tazaDos  %', (v_tasa_dos);\r\n"
					+ "raise notice '>>>> valor plazo  %', (p_plazo);*/\r\n"
					+ "end if;\r\n"
					+ "\r\n"
					+ "raise notice 'Cuota Corriente %', (r_cuota_corriente);\r\n"
					+ "\r\n"
					+ "	/*Calcular Estudio Credito IVA -  originacion*/\r\n"
					+ "r_estudio_credito_iva := ((p_monto * v_tasa_estudio_credito) / 100) + (((p_monto * v_tasa_estudio_credito) / 100) * (v_iva - 1));\r\n"
					+ "\r\n"
					+ "raise notice 'valor Estudio Credito + Iva %', (r_estudio_credito_iva);\r\n"
					+ "\r\n"
					+ "	/*Calcular Fianza -  originacion*/\r\n"
					+ "r_fianza := ((p_monto * v_tasa_fianza) / 100) * v_iva;\r\n"
					+ "\r\n"
					+ "raise notice 'valor Fianza(s) %',\r\n"
					+ "(r_fianza);\r\n"
					+ "\r\n"
					+ "	/*Calcular Gmf4*1000 -  originacion*/\r\n"
					+ "r_gmf4100 := p_vlrCompasSaneamientos * v_gmf4100;\r\n"
					+ "\r\n"
					+ "raise notice 'Valor GMF4100 %', (r_gmf4100);\r\n"
					+ "\r\n"
					+ "	/*Calular Valor Intereses Iniciales -  originacion*/\r\n"
					+ "r_valor_intereses_iniciales := ((r_monto_solicitar * p_tasaInicial) / 100) * (p_diasIniciales / v_diasMes);\r\n"
					+ "\r\n"
					+ "raise notice 'Valor Intereses Iniciales %',\r\n"
					+ "(r_valor_intereses_iniciales);\r\n"
					+ "\r\n"
					+ "	/*Calcular Prima Anticipada Seguro -  originacion*/\r\n"
					+ "r_prima_anticipada_seguro := ((p_monto / v_valor_millon)*(v_tasaXmillonSeguro * p_xperiodoPrima));\r\n"
					+ "\r\n"
					+ "raise notice 'PrimaSeguro %',\r\n"
					+ "(r_prima_anticipada_seguro);\r\n"
					+ "\r\n"
					+ "	/*Calcular Remanente Estimado -  originacion*/\r\n"
					+ "\r\n"
					+ "r_remanente_estimado := r_monto_solicitar - (p_vlrCompasSaneamientos + r_gmf4100 + r_prima_anticipada_seguro + r_estudio_credito_iva + r_fianza);\r\n"
					+ "\r\n"
					+ "raise notice 'Remanente Estimado %', (r_remanente_estimado);\r\n"
					+ "\r\n"
					+ "	/*Calcular Monto Maximo a Desembolsar -  originacion*/\r\n"
					+ "\r\n"
					+ "v_capacidad := ((p_ingresos - p_descLey) / 2) - p_descNomina - v_colchon;\r\n"
					+ "raise notice 'Capacidad Cliente %', (v_capacidad);\r\n"
					+ "\r\n"
					+ "r_capacidad_cliente := v_capacidad;\r\n"
					+ "--Logica\r\n"
					+ "if (p_plazo < v_vlr_mes_dos) then\r\n"
					+ "	r_monto_max_desembolsar := v_capacidad * ((power((1 + v_tasa_uno),(p_plazo))) - 1) / (v_tasa_uno * power((1 + v_tasa_uno),(p_plazo)));\r\n"
					+ "else \r\n"
					+ "	r_monto_max_desembolsar := v_capacidad * ((power((1 + v_tasa_uno), (v_vlr_mes_dos - 1))) - 1)\r\n"
					+ "                    / (v_tasa_uno * power((1 + v_tasa_uno), (v_vlr_mes_dos - 1)))\r\n"
					+ "                    + (v_capacidad * ((power((1 + v_tasa_dos), (p_plazo - (v_vlr_mes_dos - 1)))) - 1)\r\n"
					+ "                    / (v_tasa_dos * power((1 + v_tasa_dos), (p_plazo - (v_vlr_mes_dos - 1)))))\r\n"
					+ "                    / power((1 + v_tasa_uno), (v_vlr_mes_dos - 1));\r\n"
					+ "end if;\r\n"
					+ "\r\n"
					+ "raise notice 'Monto Maximo a Desembolsar %', (r_monto_max_desembolsar);\r\n"
					+ "\r\n"
					+ "/**********************************RETORNO DE : CALCULOS DE CONCEPTOS PARA SIMULADORES********************************************/\r\n"
					+ "return query\r\n"
					+ "select coalesce (r_monto_solicitar,0),\r\n"
					+ "coalesce (r_cuota_corriente,0), \r\n"
					+ "coalesce (r_estudio_credito_iva,0),\r\n"
					+ "coalesce (r_fianza,0),\r\n"
					+ "coalesce (r_gmf4100,0),\r\n"
					+ "coalesce (r_valor_intereses_iniciales,0),\r\n"
					+ "coalesce (r_prima_anticipada_seguro,0),\r\n"
					+ "coalesce (r_remanente_estimado,0),\r\n"
					+ "coalesce (r_monto_max_desembolsar,0),\r\n"
					+ "coalesce (r_capacidad_cliente,0);\r\n"
					+ "end;\r\n"
					+ "\r\n"
					+ "$function$");
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		
	}
	
	//Funcion Retanqueo Implementacion Jonathann Varon - ADP-172
	
	public static void ejecutarFuncionRetanqueo() {
		log.info("***Ejecutando Funcion Retanqueo ***");
		try {
			dbconector.ejecutorFunciones(
					"create or replace\r\n"
					+ "function public.calculos_simulador_interno_retanqueo_adp(\r\n"
					+ "	creditopadre numeric,\r\n"
					+ "	tasa numeric,\r\n"
					+ "	plazo numeric,\r\n"
					+ "	diashabilesintereses numeric,\r\n"
					+ "	monto numeric,\r\n"
					+ "	sumamontocarteras numeric\r\n"
					+ ")\r\n"
					+ "returns table( \r\n"
					+ "	tipocalculos character varying,\r\n"
					+ "	calculoprimaanticipadaseguro numeric,\r\n"
					+ "	calculocuotacorriente numeric,\r\n"
					+ "	resultgmf41000 numeric,\r\n"
					+ "	calculoprimanodevengada numeric,\r\n"
					+ "	calculoprimaneta numeric,\r\n"
					+ "	r_sumaFianzas numeric,\r\n"
					+ "	r_fianzaPadre numeric,\r\n"
					+ "	r_fianza_neta numeric,\r\n"
					+ "	resultestudiocredito numeric,\r\n"
					+ "	saldoaldia numeric,\r\n"
					+ "	calculoremanenteestimado numeric\r\n"
					+ ")\r\n"
					+ "language plpgsql\r\n"
					+ "as $function$\r\n"
					+ "\r\n"
					+ "declare\r\n"
					+ "-- constantes\r\n"
					+ "iva numeric = 1.19;\r\n"
					+ "tasaXmillon numeric = 4625;\r\n"
					+ "gmf41000 numeric = 0.004;\r\n"
					+ "tasaUno numeric = tasa / 100;\r\n"
					+ "variableMillon numeric = 1000000;\r\n"
					+ "-- variables de calculos\r\n"
					+ "calculoPrimaAnticipadaSeguro numeric;\r\n"
					+ "calculoEstudioCreditoHijo numeric;\r\n"
					+ "calculoValorFianza numeric;\r\n"
					+ "calculoPrimaNeta numeric;\r\n"
					+ "calculoPrimaNoDevengada numeric;\r\n"
					+ "calculoCuotaCorriente numeric;\r\n"
					+ "calculoRemanenteEstimado numeric;\r\n"
					+ "-- variables\r\n"
					+ "tienePrimaPadre varchar;\r\n"
					+ "descuentoPrimaAnticipada numeric;\r\n"
					+ "fianzaPadre numeric;\r\n"
					+ "estudioCreditoPadre numeric;\r\n"
					+ "idCredito integer;\r\n"
					+ "v_nombrePagaduria text;\r\n"
					+ "idPagaduria integer;\r\n"
					+ "estudioCredito numeric;\r\n"
					+ "tasaFianza numeric;\r\n"
					+ "tasaDos numeric;\r\n"
					+ "mesDos numeric;\r\n"
					+ "periodoGracia numeric;\r\n"
					+ "primaPadre numeric;\r\n"
					+ "montoPadre numeric;\r\n"
					+ "mesesActivosPadre numeric;\r\n"
					+ "tipoCalculos varchar;\r\n"
					+ "r_fianza_neta numeric;\r\n"
					+ "resultEstudioCredito numeric;\r\n"
					+ "resultGmf41000 numeric;\r\n"
					+ "saldoAlDia numeric;\r\n"
					+ "\r\n"
					+ "begin\r\n"
					+ "-- consultar prima padre\r\n"
					+ "select\r\n"
					+ "	case\r\n"
					+ "		when c.numero_radicacion = null then 'true'\r\n"
					+ "		else 'false'\r\n"
					+ "	end as prima\r\n"
					+ "into\r\n"
					+ "	tienePrimaPadre\r\n"
					+ "from\r\n"
					+ "	credito c\r\n"
					+ "inner join desglose d on\r\n"
					+ "	d.id_credito = c.id\r\n"
					+ "inner join prima_seguro_anticipada ps on\r\n"
					+ "	ps.id_desglose = d.id\r\n"
					+ "where\r\n"
					+ "	1 = 1\r\n"
					+ "	and d.desglose_seleccionado is true\r\n"
					+ "	and c.credito_activo is true\r\n"
					+ "	and c.numero_radicacion = creditoPadre;\r\n"
					+ "-- consulta el descuento de la prima anticipada\r\n"
					+ "select\r\n"
					+ "	valor\r\n"
					+ "into\r\n"
					+ "	descuentoPrimaAnticipada\r\n"
					+ "from\r\n"
					+ "	parametro_configuracion\r\n"
					+ "where\r\n"
					+ "	nombre = 'PRIMA_SEGURO_PERIODOS_DESCONTAR'\r\n"
					+ "order by\r\n"
					+ "	id desc;\r\n"
					+ "-- consulta para obtener la fianza padre\r\n"
					+ "select\r\n"
					+ "	coalesce(round(d.valor_fianza), 0) fianzaPadre\r\n"
					+ "into\r\n"
					+ "	fianzaPadre\r\n"
					+ "from\r\n"
					+ "	desglose d\r\n"
					+ "where\r\n"
					+ "	id_credito in (\r\n"
					+ "	select\r\n"
					+ "		id\r\n"
					+ "	from\r\n"
					+ "		credito\r\n"
					+ "	where\r\n"
					+ "		numero_radicacion = creditoPadre)\r\n"
					+ "	and desglose_seleccionado is true\r\n"
					+ "limit 1;\r\n"
					+ "-- consulta para obtener el id del credito y la pagadurÃ­a\r\n"
					+ "select\r\n"
					+ "	c.id,\r\n"
					+ "	c.id_pagaduria,\r\n"
					+ "	p.nombre\r\n"
					+ "into\r\n"
					+ "	idCredito,\r\n"
					+ "	idPagaduria,\r\n"
					+ "	v_nombrePagaduria\r\n"
					+ "from\r\n"
					+ "	credito c\r\n"
					+ "join pagaduria p on\r\n"
					+ "	p.id = c.id_pagaduria\r\n"
					+ "where\r\n"
					+ "	numero_radicacion = creditoPadre;\r\n"
					+ "\r\n"
					+ "raise notice 'Pagaduria %',\r\n"
					+ "v_nombrePagaduria;\r\n"
					+ "-- consultar el saldo al dia\r\n"
					+ "select\r\n"
					+ "	saldo_al_dia\r\n"
					+ "into\r\n"
					+ "	saldoAlDia\r\n"
					+ "from\r\n"
					+ "	saldo_al_dia sad\r\n"
					+ "where\r\n"
					+ "	id_credito = idCredito;\r\n"
					+ "-- cunsulta para obtener el estudio del credito padre\r\n"
					+ "select\r\n"
					+ "	coalesce(round(obtener_valor_estudio_credito(current_date, idCredito, idPagaduria, false)), 0) estudioCreditoPadre\r\n"
					+ "into\r\n"
					+ "	estudioCreditoPadre;\r\n"
					+ "-- consulta para obtener valores capitalizador\r\n"
					+ "select\r\n"
					+ "	estudio_credito,\r\n"
					+ "	segunda_tasa,\r\n"
					+ "	fianza,\r\n"
					+ "	mes_cambio_tasa\r\n"
					+ "into\r\n"
					+ "	estudioCredito,\r\n"
					+ "	tasaDos,\r\n"
					+ "	tasaFianza,\r\n"
					+ "	mesDos\r\n"
					+ "from\r\n"
					+ "	configuracion_capitalizacion_cxc ccc\r\n"
					+ "where\r\n"
					+ "	tasa_inicial = tasa;\r\n"
					+ "-- calcular periodo de gracia\r\n"
					+ "if (plazo < descuentoPrimaAnticipada)\r\n"
					+ "	then\r\n"
					+ "		periodoGracia = ceiling(diasHabilesIntereses / 30);\r\n"
					+ "\r\n"
					+ "descuentoPrimaAnticipada = periodoGracia + plazo;\r\n"
					+ "end if;\r\n"
					+ "-- calcular prima credito padre\r\n"
					+ "select\r\n"
					+ "	round(valor)\r\n"
					+ "into\r\n"
					+ "	primaPadre\r\n"
					+ "from\r\n"
					+ "	prima_seguro_anticipada psa\r\n"
					+ "join desglose d2\r\n"
					+ "on\r\n"
					+ "	d2.id = psa.id_desglose\r\n"
					+ "join credito c2\r\n"
					+ "on\r\n"
					+ "	c2.id = d2.id_credito\r\n"
					+ "where\r\n"
					+ "	d2.desglose_seleccionado is true\r\n"
					+ "	and c2.numero_radicacion = creditoPadre;\r\n"
					+ "-- consultar monto padre\r\n"
					+ "select\r\n"
					+ "	round(c2.monto_aprobado)\r\n"
					+ "into\r\n"
					+ "	montoPadre\r\n"
					+ "from\r\n"
					+ "	prima_seguro_anticipada psa\r\n"
					+ "join desglose d2\r\n"
					+ "on\r\n"
					+ "	d2.id = psa.id_desglose\r\n"
					+ "join credito c2\r\n"
					+ "on\r\n"
					+ "	c2.id = d2.id_credito\r\n"
					+ "where\r\n"
					+ "	d2.desglose_seleccionado is true\r\n"
					+ "	and c2.numero_radicacion = creditoPadre;\r\n"
					+ "-- consultar meses activos padre\r\n"
					+ "with ConteoPeriodos as (\r\n"
					+ "select\r\n"
					+ "	(count(fechas)+ complemento-1) periodos\r\n"
					+ "from\r\n"
					+ "	(\r\n"
					+ "	select\r\n"
					+ "		id_credito,\r\n"
					+ "		generate_series(mes_contable, now(), cast('1 month' as interval) )fechas,\r\n"
					+ "		case\r\n"
					+ "			when date_part('day', now()) < date_part('day', mes_contable) then 1\r\n"
					+ "			else 0\r\n"
					+ "		end complemento\r\n"
					+ "	from\r\n"
					+ "		movimiento_contable as mc\r\n"
					+ "	where\r\n"
					+ "		id_credito in(\r\n"
					+ "		select\r\n"
					+ "			c2.id\r\n"
					+ "		from\r\n"
					+ "			credito c2\r\n"
					+ "		where\r\n"
					+ "			c2.numero_radicacion = creditoPadre)\r\n"
					+ "		and tipo_transaccion = 'ACTIVACION_CREDITO'\r\n"
					+ ") x\r\n"
					+ "group by\r\n"
					+ "	complemento,\r\n"
					+ "	id_credito\r\n"
					+ ")\r\n"
					+ "select\r\n"
					+ "	periodos\r\n"
					+ "into\r\n"
					+ "	mesesActivosPadre\r\n"
					+ "from\r\n"
					+ "	ConteoPeriodos;\r\n"
					+ "-- se realizan los calculos\r\n"
					+ "-- calcular prima anticipada de seguro\r\n"
					+ "calculoPrimaAnticipadaSeguro = round(monto / (1 + (estudioCredito / 100) * iva + (tasaFianza / 100)\r\n"
					+ "							 * iva + tasaXmillon / 1000000 * descuentoPrimaAnticipada) * tasaXmillon\r\n"
					+ "							 * descuentoPrimaAnticipada / 1000000);\r\n"
					+ "\r\n"
					+ "raise notice 'PrimaAnticipada %',\r\n"
					+ "(calculoPrimaAnticipadaSeguro);\r\n"
					+ "-- calcular cuota corriente\r\n"
					+ "if(plazo < mesDos) then\r\n"
					+ "  calculoCuotaCorriente = monto / ((power((1 + tasaUno), (plazo)) - 1) / (tasaUno * power((1 + tasaUno), (plazo))));\r\n"
					+ "else\r\n"
					+ "  tasaDos = tasaDos / 100;\r\n"
					+ "\r\n"
					+ "calculoCuotaCorriente = round(monto\r\n"
					+ "  / ((power((1 + tasaUno), (mesDos - 1)) - 1) / (tasaUno * power((1 + tasaUno), (mesDos - 1)))\r\n"
					+ "  + ((power((1 + tasaDos), (plazo - (mesDos - 1))) - 1)\r\n"
					+ "  / (tasaDos * power((1 + tasaDos), (plazo - (mesDos - 1)))))\r\n"
					+ "  / (power((1 + tasaUno), (mesDos - 1)))));\r\n"
					+ "end if;\r\n"
					+ "\r\n"
					+ "raise notice 'CuotaCorriente %',\r\n"
					+ "(calculoCuotaCorriente);\r\n"
					+ "-- calcular 4*1000\r\n"
					+ "resultGmf41000 = round(sumaMontoCarteras * gmf41000);\r\n"
					+ "\r\n"
					+ "raise notice '4X100  %',\r\n"
					+ "(resultGmf41000);\r\n"
					+ "-- calcular prima no devengada\r\n"
					+ "calculoPrimaNoDevengada = round(coalesce(primaPadre, 0) - ((coalesce(montoPadre, 0) * tasaXmillon) / variableMillon) * mesesActivosPadre);\r\n"
					+ "\r\n"
					+ "raise notice 'Prima no devengada  %',\r\n"
					+ "(calculoPrimaNoDevengada);\r\n"
					+ "-- calcular prima neta\r\n"
					+ "calculoPrimaNeta = calculoPrimaAnticipadaSeguro - calculoPrimaNoDevengada;\r\n"
					+ "\r\n"
					+ "raise notice 'Prima Neta  %',\r\n"
					+ "(calculoPrimaNoDevengada);\r\n"
					+ "-- calcular estudio de credito retanqueo hijo\r\n"
					+ "calculoEstudioCreditoHijo = round(monto / (1 + (estudioCredito / 100) * iva + (tasaFianza / 100) * iva +\r\n"
					+ "							(tasaXmillon / 1000000 * descuentoPrimaAnticipada)) * (estudioCredito / 100) * iva);\r\n"
					+ "\r\n"
					+ "raise notice 'EstudioCredito  %',\r\n"
					+ "(calculoPrimaNoDevengada);\r\n"
					+ "-- calcular valor de la fianza\r\n"
					+ "calculoValorFianza = round(monto / (1 + ((estudioCredito / 100) * iva) + ((tasaFianza / 100) * iva)\r\n"
					+ "                	 + (tasaXmillon / 1000000) * descuentoPrimaAnticipada) * (tasaFianza / 100) * iva);\r\n"
					+ "-- result fianza\r\n"
					+ "r_fianza_neta = calculoValorFianza - fianzaPadre;\r\n"
					+ "\r\n"
					+ "if (r_fianza_neta < 0)\r\n"
					+ "  then\r\n"
					+ "  r_fianza_neta = 0;\r\n"
					+ "end if;\r\n"
					+ "\r\n"
					+ "r_sumaFianzas := (fianzaPadre + r_fianza_neta);\r\n"
					+ "\r\n"
					+ "r_fianzaPadre := fianzaPadre;\r\n"
					+ "\r\n"
					+ "raise notice 'Suma Fianzas %',\r\n"
					+ "(r_sumaFianzas);\r\n"
					+ "\r\n"
					+ "raise notice 'Fianza Padre %',\r\n"
					+ "(fianzaPadre);\r\n"
					+ "\r\n"
					+ "raise notice 'Fianza Neta %',\r\n"
					+ "(r_fianza_neta);\r\n"
					+ "-- calculo remanente estimado\r\n"
					+ "calculoRemanenteEstimado = round(monto - (saldoAlDia + r_fianza_neta + estudioCredito + sumaMontoCarteras + resultGmf41000 + calculoPrimaAnticipadaSeguro));\r\n"
					+ "\r\n"
					+ "raise notice 'RemanenteEstimado  %',\r\n"
					+ "(calculoRemanenteEstimado);\r\n"
					+ "-- estudio de crÃ©dito\r\n"
					+ "resultEstudioCredito = calculoEstudioCreditoHijo - estudioCreditoPadre;\r\n"
					+ "\r\n"
					+ "if (resultEstudioCredito < 0)\r\n"
					+ "  then\r\n"
					+ "  resultEstudioCredito = 0;\r\n"
					+ "end if;\r\n"
					+ "\r\n"
					+ "raise notice 'EstudioCredito  %',\r\n"
					+ "(resultEstudioCredito);\r\n"
					+ "-- validaciones si es anticipado o mensualizado\r\n"
					+ "if (tienePrimaPadre = '')\r\n"
					+ "	then\r\n"
					+ "		tipoCalculos = 'mensualizado';\r\n"
					+ "else\r\n"
					+ "		tipoCalculos = 'anticipado';\r\n"
					+ "end if;\r\n"
					+ "-- return values\r\n"
					+ "return query\r\n"
					+ "select\r\n"
					+ "	tipoCalculos,\r\n"
					+ "	coalesce(calculoPrimaAnticipadaSeguro, 0),\r\n"
					+ "	coalesce(calculoCuotaCorriente, 0),\r\n"
					+ "	coalesce(resultGmf41000, 0),\r\n"
					+ "	coalesce(calculoPrimaNoDevengada, 0),\r\n"
					+ "	coalesce(calculoPrimaNeta, 0),\r\n"
					+ "	coalesce(r_sumaFianzas, 0),\r\n"
					+ "	coalesce(fianzaPadre, 0),\r\n"
					+ "	coalesce(r_fianza_neta, 0),\r\n"
					+ "	coalesce(resultEstudioCredito, 0),\r\n"
					+ "	coalesce(saldoAlDia, 0),\r\n"
					+ "	coalesce(calculoRemanenteEstimado, 0);\r\n"
					+ "end;\r\n"
					+ "\r\n"
					+ "$function$");
		} catch (Exception e) {
			log.error(e.getMessage());
		}
	}
}
