#language: es
Característica: Originacion de Creditos

  Antecedentes: 
    Dado Un agente en el sistema core abacus con sesion iniciada

  @SolicitudCredito
  Esquema del escenario: Solicitar credito Digicredito
    Cuando el agente ingrese a la pestana solicitud filtra por el numero de radicacion del credito <NumRadicacion><primerNombre>
    Y carga todos los archivos en la pestana de digitalizacion <rutaPDF>
    Y marcar los check en correcto guardando en la pestana de digitalizacion
    Y se llenan los campos obligatorios en la pestana formulario guardando digicredito <DestinoCredito><genero><EstadoCivil><direccionResidencia><departamento><ciudad><TipoVivienda><Correo><Celular><tipocontratoAbacus>
    Y se agregar las referencias en la segunta pestana del formulario guardando Digicredito <Ingresos><TotalActivos><PapellidoReferencia><PnombreReferencia><direccionResidencia><TelefonoResidencia><TelefonoTrabajo><departamento><ciudad>
    Y se presiona en verificacion en la pestana digitalizacion
    Y se pasa a la segunda pestana de digitalizacion se agrega el codigo proforences aprueba referencias digicredito <Codigo>
    Y se marca identidida confirmada radicando la solicitud
    Entonces se aprueba la referenciacion de la pagaduria en la pestana referenciacion permite realizar la solicitud del analisis

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @SolicitudCreditoCCS
  Esquema del escenario: Solicitar credito Digicredito
    Cuando el agente ingrese a la pestana solicitud filtra por el numero de radicacion del credito <NumRadicacion><primerNombre>
    Y carga todos los archivos en la pestana de digitalizacion <rutaPDF>
    Y marcar los check en correcto guardando en la pestana de digitalizacion
    Y se llenan los campos obligatorios en la pestana formulario guardando digicredito <DestinoCredito><genero><EstadoCivil><direccionResidencia><departamento><ciudad><TipoVivienda><Correo><Celular><tipocontratoAbacus>
    Y se agregar las referencias en la segunta pestana del formulario guardando Digicredito <Ingresos><TotalActivos><PapellidoReferencia><PnombreReferencia><direccionResidencia><TelefonoResidencia><TelefonoTrabajo><departamento><ciudad>
    Y se presiona en verificacion en la pestana digitalizacion
    Y se crean los tipos de cartera o saneamiento a recoger creados en digicredito
    Y se guarda cartera
    Y se pasa a la primera pestana de referenciacion para confirmar la entidad
      | Tipo    | Entidad                          | Monto  | VlrCuota | FechaVencimiento | NumObligacion |
      | Cartera | 8060045257 - ABOGADAS Y ASESORES | 300000 |    60000 | 30/12/2022       |         29124 |
      | Cartera | 8060045257 - ABOGADAS Y ASESORES | 200000 |    50000 | 30/12/2022       |         21237 |
      | Cartera | 8060045257 - ABOGADAS Y ASESORES | 100000 |    50000 | 30/12/2022       |         21237 |
    Y se pasa a la segunda pestana de digitalizacion se agrega el codigo proforences <Codigo>
    Y se marca identidida confirmada radicando la solicitud
    Entonces se aprueba la referenciacion de la pagaduria en la pestana referenciacion permite realizar la solicitud del analisis

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @AnalisisCredito
  Esquema del escenario: Analisis del credito creado en digicredito
    Cuando el agente ingresa a pestana analisis de credito busca con la cedula del cliente <Cedula><primerNombre>
    Y ingresa los valores guardando <Ingresos><descLey><descNomina>
    Y pasa a la siguiente pestana del simulador analista
    Entonces Valida los valores del simulador<Mes><montoSolicitado><Tasa><Plazo><Ingresos><descLey><descNomina><Pagaduria><vlrCompasSaneamientos><AnoAnalisis><fechaDesembolso>
    Y Guarda los datos del simulador
    Y ingrese a la pestana del plan de pagos
    Y valide la informacion cabecera con sus conceptos para Originacion<Tasa><Plazo>
    Y Validacion de saldo a capital en el desgloce del plan de pagos con el ultimo<Plazo>
    Y Pasa a la pestana endeudamiento global aprobando
    Y Aprueba la tarea del credito<Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @AnalisisCreditoCCS
  Esquema del escenario: Analisis del credito con compra de cartera y saneamiento
    Cuando el agente ingresa a pestana analisis de credito busca con la cedula del cliente <Cedula><primerNombre>
    Y ingresa los valores guardando <Ingresos><descLey><descNomina>
    Y pasa a la siguiente pestana del simulador analista
    Entonces Valida los valores del simulador para compra de cartera con saneamiento <Mes><montoSolicitado><Tasa><Plazo><Ingresos><descLey><descNomina><Pagaduria><Cartera1><Saneamiento2><AnoAnalisis><fechaDesembolso>
    Y Guarda los datos del simulador
    Y ingrese a la pestana del plan de pagos
    Y valide la informacion cabecera con sus conceptos para OriginacionCCS<Tasa><Plazo>
    Y Validacion de saldo a capital en el desgloce del plan de pagos con el ultimo<Plazo>
    Y Pasa a la pestana endeudamiento global aprobando
    Y Aprueba la tarea del credito<Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @ClientesBienvenida
  Esquema del escenario: Clientes para Bienvenida
    Cuando el agente ingresa a la pestana clientes para bienvenida<Cedula>
    Y se marcar los check correctos junto con el celular y correo<Celular> <Correo>
    Y se validan los valores de las condiciones del credito <Ingresos><descLey><descNomina><Pagaduria>
    Y se marcan los chech y se acepta el detalle originacion<TipoDesen><Cedula>
    Entonces se ingresa el codigo OTP <Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @ClientesBienvenidaCCS
  Esquema del escenario: Clientes para Bienvenida
    Cuando el agente ingresa a la pestana clientes para bienvenida<Cedula>
    Y se marcar los check correctos junto con el celular y correo<Celular> <Correo>
    #Y se validan los valores de las condiciones del credito <Ingresos><descLey><descNomina><Pagaduria>
    Y se marcan los chech y se acepta carteras y saneamientos <TipoDesen><Cedula>
    Entonces se ingresa el codigo OTP <Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @CreditosVisacion
  Esquema del escenario: Creditos para Visacion
    Cuando el agente ingresa a la pestana clientes para Visacion <Cedula>
    Y se marca aprobado se selecciona la fecha aprobando<fechaActual><rutaPDF>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @Desembolso
  Esquema del escenario: Creditos para Desembolso
    Cuando el agente ingresa a la pestana Desembolso lista de pagos <Cedula>
    Y se marca el check aprobando el proceso de pagos
    Y se filtra por monto y se edita <montoSolicitado><Banco><rutaPDF>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @ValidarDinamicasContablesOriginacion
  Esquema del escenario: Validar dinamicas contables ORIGINACION CREDITO
    Cuando el sistema valida por <Credito> y <Cedula> en la tabla movimiento contable las <AccountingSource> que se proceso por el bridge en la <FechaRegistro>
    Y valide la causacion de movimientos <AccountingSource> con sus tipos y valores usando el <Credito> en la <FechaRegistro>
    Y valida que las cuentas de libranzas <AccountingSource> sean las del bridge <AccountingName> con el <Credito> y <Cedula> en la <FechaRegistro>
    Entonces finalmente se valida la transaccion <AccountingSource> con <FechaRegistro> en la base de datos de PSL con el <Credito>

    Ejemplos: 
      | Pagaduria   | Cedula     | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes       | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual     | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                              | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos            | fechaNacimiento | Contacto                | lineaCredito      | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataOriginacion.xlsx@OriginacionDigiCredito
   |"COLFONDOS"   |"52912399"   |"1.70"   |"50"   |"7349400"   |"50"   |"8500000"   |"250000"   |"300000"   |"Febrero"   |"05/05/2022"   |"ALEYDA"   |""   |"RODRIGUEZ"   |"GONZALEZ"   |"02/Marzo/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"prueba123@gmail.com"   |"3125127717"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2022   |"0"   |"0"   |"86313"   |"ALEYDA RODRIGUEZ GONZALEZ"   |"15/02/1956"   |"Entidad donde trabaja"   |"Libre inversion"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"Si"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|
