#language: es
Característica: Retanqueo de creditos

  Antecedentes: 
    Dado Un agente en el sistema core abacus con sesion iniciada

  @RetanqueoSolicitudMultipleDigi
  Esquema del escenario: Retanqueo libre inversion digicredito Multiple
    Cuando se busca el credito por <Cedula>
    Y se selecciona el retanqueo
    Y cargar archivos nuevos <rutaPDF>
    Y carga todos los archivos en la pestana de digitalizacion <rutaPDF>
    Y marcar los check en correcto guardando en la pestana de digitalizacion
    Y se presiona en verificacion en la pestana digitalizacion
    Y se confirma identidad en digitalizacion <codigo>
    Y se marca identidida confirmada radicando la solicitud
    Y se aprueban las referencias de la pagaduria
    Entonces se aprueba la referenciacion de la pagaduria en la pestana referenciacion permite realizar la solicitud del analisis

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoMultiple
   |"P.A COLPENSIONES"   |"14448030"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"18/03/2022"   |"JOSE"   |""   |"JOAQUIN"   |"ERAZO"   |"18/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"0"   |"0"   |"81768"   |"JOSE JOAQUIN ERAZO "   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @AnalisisCreditoRetanqueoMultipleDigi
  Esquema del escenario: Analisis del credito Multiple
    Cuando el agente ingresa a pestana analisis de credito busca con la cedula del cliente <Cedula><primerNombre>
    Y ingresa los valores guardando <Ingresos><descLey><descNomina>
    Y pasa a la siguiente pestana del simulador analista
    Entonces Valida los valores del simulador retanqueo multiple <Cedula><Pagaduria><DiasHabilesIntereses><AnnoAfetacion><montoSolicitado><fechaActual><Mes><Plazo><Tasa><vlrCompasSaneamientos>
    Y Guarda los datos del simulador
    Y ingrese a la pestana del plan de pagos
    Y valide la informacion cabecera con sus conceptos para Retanqueo<Tasa><Plazo>
    Y Validacion de saldo a capital en el desgloce del plan de pagos con el ultimo<Plazo>
    Y Pasa a la pestana endeudamiento global aprobando
    Y Aprueba la tarea del credito<Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoMultiple
   |"P.A COLPENSIONES"   |"14448030"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"18/03/2022"   |"JOSE"   |""   |"JOAQUIN"   |"ERAZO"   |"18/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"0"   |"0"   |"81768"   |"JOSE JOAQUIN ERAZO "   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @ClientesBienvenidaRetanqueosMultipleDigi
  Esquema del escenario: Clientes para Bienvenida Retanqueo Digicredito Multiple
    Cuando el agente ingresa a la pestana clientes para bienvenida<Cedula>
    Y se marcar los check correctos junto con el celular y correo<Celular> <Correo>
    Y se marcan los chech y se acepta <TipoDesen><Cedula>
    Entonces se ingresa el codigo OTP <Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoMultiple
   |"P.A COLPENSIONES"   |"14448030"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"18/03/2022"   |"JOSE"   |""   |"JOAQUIN"   |"ERAZO"   |"18/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"0"   |"0"   |"81768"   |"JOSE JOAQUIN ERAZO "   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

   @CreditosVisacionRetanqueosMultipleDigi
  Esquema del escenario: Creditos para Visacion multiple de Digicredito
    Cuando el agente ingresa a la pestana clientes para Visacion <Cedula>
    Y se marca aprobado se selecciona la fecha aprobando<fechaActual><rutaPDF>

    Ejemplos: 
       | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoMultiple
   |"P.A COLPENSIONES"   |"14448030"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"18/03/2022"   |"JOSE"   |""   |"JOAQUIN"   |"ERAZO"   |"18/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"thainer.perez@gmail.com"     |"3133421083"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2022"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"0"   |"0"   |"81768"   |"JOSE JOAQUIN ERAZO "   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92840"   |"Pensionado por Invalidez"|

  @DesembolsoRetanqueos
  Esquema del escenario: Creditos para Desembolso
   Cuando el agente ingresa a la pestana Desembolso lista de pagos <Cedula>
    Y se marca el check aprobando el proceso de pagos
    Y se filtra por monto para retanqueo y se edita <Banco><rutaPDF><Cedula><Tasa><Credito><Plazo><DiasHabilesIntereses><vlrCompasSaneamientos> 
   
    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCredito
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"0"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"0"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92845"   |"Pensionado por Invalidez"|



##Retanqueo Multiple Compra de carteras
  @RetanqueoCCS
  Esquema del escenario: Retanqueo Compra de cartera y saneamiento Digicredito
    Cuando el agente ingrese a la pestana solicitud filtra por el numero de radicacion del credito <NumRadicacion><primerNombre>
    Y cargar archivos nuevos <rutaPDF>
    Y carga todos los archivos en la pestana de digitalizacion <rutaPDF>
    Y marcar los check en correcto guardando en la pestana de digitalizacion
    Y se presiona en verificacion en la pestana digitalizacion
    Y se crean los tipos de cartera o saneamiento a recoger creados en digicredito
    Y se guarda cartera
    Y se pasa a la primera pestana de referenciacion para confirmar la entidad
      | Tipo    | Entidad                          | Monto  | VlrCuota | FechaVencimiento | NumObligacion |
      | Cartera | 8060045257 - ABOGADAS Y ASESORES | 100000 |    60000 | 30/03/2022       |         29124 |
      | Cartera | 8060045257 - ABOGADAS Y ASESORES | 100000 |    50000 | 30/03/2022       |         21237 |
   #   | Cartera | 8060045257 - ABOGADAS Y ASESORES | 100000 |    50000 | 30/12/2022       |         21237 |
    Y se confirma identidad en digitalizacion <codigo>
    Y se marca identidida confirmada radicando la solicitud
    Y se aprueban las referencias de la pagaduria
    Entonces se aprueba la referenciacion de la pagaduria en la pestana referenciacion permite realizar la solicitud del analisis

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @AnalisisCreditoRetanqueoCCS
  Esquema del escenario: Analisis del credito
    Cuando el agente ingresa a pestana analisis de credito busca con la cedula del cliente <Cedula><primerNombre>
    Y ingresa los valores guardando <Ingresos><descLey><descNomina>
    Y pasa a la siguiente pestana del simulador analista
    Entonces Valida los valores del simulador retanqueos con compra de cartera y saneamiento <AnnoAfetacion><Credito><montoSolicitado><fechaActual><Mes><Plazo><Ingresos><descLey><descNomina><Cartera1><Saneamiento2><DiasHabilesIntereses><Tasa>
    Y Guarda los datos del simulador
    Y ingrese a la pestana del plan de pagos
    Y valide la informacion cabecera con sus conceptos para Retanqueo<Tasa><Plazo>
    Y Validacion de saldo a capital en el desgloce del plan de pagos con el ultimo<Plazo>
    Y Pasa a la pestana endeudamiento global aprobando
    Y Aprueba la tarea del credito<Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @ClientesBienvenidaRetanqueoCCS
  Esquema del escenario: Clientes para Bienvenida
    Cuando el agente ingresa a la pestana clientes para bienvenida<Cedula>
    Y se marcar los check correctos junto con el celular y correo<Celular> <Correo>
    #Y se validan los valores de las condiciones del credito <Credito><Plazo><DiasHabilesIntereses>
    Y se marcan los chech y se acepta carteras y saneamientos <TipoDesen><Cedula>
    Entonces se ingresa el codigo OTP <Cedula>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @CreditosVisacionRetanqueosCCS
  Esquema del escenario: Creditos para Visacion
    Cuando el agente ingresa a la pestana clientes para Visacion <Cedula>
    Y se marca aprobado se selecciona la fecha aprobando<fechaActual><rutaPDF>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @DesembolsoCarteraCCS
  Esquema del escenario: Carteras para Desembolso
    Cuando el agente ingresa a la lista de pagos para procesar "Cartera" con <Cedula>
    Y se descargan medios de dispersion para la cartera
      | Monto  | Banco                                            | RutaPdf                               |
      | 300000 | Bancolombia Remanentes - 60237038927 - REMANENTE | src/test/resources/Data/PDFPRUEBA.pdf |

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @VisacionSaneamientoCCS
  Esquema del escenario: Visacion de la cartera
    Cuando el agente ingresa a la pestana clientes para Visacion <Cedula>
    Y se navega hasta carteras <rutaPDF>

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @DesembolsoSaneamientoCCS
  Esquema del escenario: Saneamiento para Desembolso
    Cuando el agente ingresa a la lista de pagos para procesar "Saneamiento" con <Cedula>
    Y se descargan medios de dispersion para la cartera
      | Monto  | Banco                                | RutaPdf                               |
      | 830000 | Remanentes - 60237038927 - REMANENTE | src/test/resources/Data/PDFPRUEBA.pdf |

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|

  @DesembolsoRetanqueosCCS
  Esquema del escenario: Creditos para Desembolso
    Cuando el agente ingresa a la pestana Desembolso lista de pagos <Cedula>
    Y se marca el check aprobando el proceso de pagos
    Cuando el agente ingresa a la lista de pagos para procesar el remanente <Cedula>
    Y se filtra por monto para retanqueo y se edita <Banco><rutaPDF><Cedula><Tasa><Credito><Plazo><DiasHabilesIntereses><vlrCompasSaneamientos>
    Y se valida el estado del credito padre <Credito><fechaActual>
      | 

    Ejemplos: 
      | Pagaduria   | Cedula    | Tasa   | Plazo | montoSolicitado | DiasHabilesIntereses | Ingresos  | descLey  | descNomina | Mes     | fechaDesembolso | primerNombre | segundoNombre | primerApellido | segundoApellido | fechaActual  | oficinaAsesor | Actividad    | TotalActivos | vlrCompasSaneamientos | TipoContrato | FechaIngreso | Correo                   | Celular      | departamento   | ciudad     | rutaPDF                                 | DestinoCredito     | genero | EstadoCivil | direccionResidencia | TipoVivienda | PapellidoReferencia | PnombreReferencia | TelefonoResidencia | TelefonoTrabajo | Codigo | AnoAnalisis | TipoDesen  | Banco                                  | AccountingSource   | AccountingName                                                          | FechaRegistro | Cartera1 | Saneamiento2 | Credito | nombresApellidos           | fechaNacimiento | Contacto                | lineaCredito                | estadoActual | page | codigo  | fechaExpedicion | estrado     | claseVivienda | posicionHogar   | nivelEscolaridad | cuotaHipotecaria | tipoDocNomina            | otrosIngresos | modalidadDesembolso      | tipoCliente | paisNacimiento | lugarDeNacimiento | nacionalidad | profesion   | mesesResidencia | numeroHijos | personasACargo | tipoPension | codigoProgramaNomina | fechaTerminacion | nitAfiliacion | tipoDocumento           | cargo | nombreBeneficario    | documentoBeneficiario | celularBeneficiario | monedaExtranjera | tipoTransanccion | productoBancario | banco       | numProducto | tipoProducto         | pais       | ciudadExt | monto  | moneda  | funcionarioPublico | recursosPublicos | expuestoPoliticamente | fechaExpuesto | Mes       | fecha        | AnnoAfetacion | fechaActual  | Banco                                              | vinculo     | plan     | tomarSeguroAP | nombresSeguroAP | parentescoSeguroAP | pNombreRefP | sNombreRefP | pApellidoRefP | sApellidoRefP | relacionRefP | celRefP      | pNombreRefF | sNombreRefF | pApellidoRefF | sApellidoRefF | relacionRefF | celRefF      | decisionExcepcion | NumRadicacion | tipocontratoAbacus         |
      ##@externaldata@./src/test/resources/Data/AutomationDataRetanqueo.xlsx@RetanqueoDigiCreditoCCS
   |"COLFONDOS"   |"5744075"   |"1.70"   |"50"   |"50500000"   |"50"   |"8500000"   |"250000"   |"300000"   |"Marzo"   |"07/03/2022"   |"DELIO"   |"ARNULFO"   |"ROJAS"   |"GUIO"   |"09/03/2022"   |"Soacha"   |"Pensionado"   |"20500000"   |"300000"   |"Jubilados"   |"10/03/2000"   |"daabogadog@hotmail.com"    |"3142739038"   |"Cundinamarca"   |"Anapoima"   |"src/test/resources/Data/PDFPRUEBA.pdf"   |"Educacion propia"   |"M"   |"Soltera/o"   |"Calle 2d #22-52"   |"Arriendo"   |"perez"   |"alejandro"   |"7210273"   |"9007146"   |"3112"   |"2021"   |"Efectivo"   |"Remanentes - 60237038927 - REMANENTE"   |"'ACRED','EGRESO'"    |"upper('Desembolso egreso'), upper('Desembolso activación de crédito')"   |29/10/2021   |"300000"   |"0"   |"81768"   |"DELIO ARNULFO ROJAS GUIO"   |"15/02/1956"   |"Entidad donde trabaja"   |"Retanqueo libre inversión"   |""   |""   |"12345"   |"06/08/1976"    |"Estrato 1"    |"Casa"   |"Jefe de hogar"   | "Universitario"    |"100000"   |"Desprendible de nómina"    |"5000000"   |"Pago masivo (efectivo)"    |"AAA"   |"colombia"   |"colombia"   |"colombiano"   |"ingeniero"    |"24"   |"2"      |"0"   |"pension"   |"123456"     |"30/12/2022"   |"123456"   |"Certificación laboral"   |"CEO"   |"Luis Perez Ramirez"   |"1234567890"   |"3183903022"   |"No"   |"Importaciones"   |"No"   |"Santander"   |"966855"   |"Inversiones en oro"    |"Alemania"   |"Berlin"   |"8500"   |"Euros"   |"No"   |"No"   |"No"   |"12/12/2008"   |"Febrero"   |"20/07/1963"   |"2022"   |"16/02/2022"   |"Bancolombia Remanentes - 60237038927 - REMANENTE"    |"Vinculado"   |"Plan 1"   |"No"   |"Juli Macias"   |"Prima"   |"maria"   |"camila"   |"lopez"   |"cardenas"   |"Amigo"   |"3204567894"   |"juan"   |"david"   |"reyes"   |"sanchez"   |"Hijo"   |"3204047804"   |"No"   |"92847"   |"Pensionado por Invalidez"|
